# pyproject.toml
[build-system]
requires = ["setuptools >= 42.0.0"]
build-backend = "setuptools.build_meta"
[project]
    name='pentomino'
    version='1.0'
    requires-python='>=3.12'
    dependencies=[
        'matplotlib',
        'numpy',
        'scikit-image',
    ]
    readme='README.md'
